version: "3"

services:
  prometheus:
    image: prom/prometheus:v2.28.0
    ports:
      - 9090:9090
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus-data:/prometheus
    command: --web.enable-lifecycle  --config.file=/etc/prometheus/prometheus.yaml

  grafana:
    image: grafana/grafana:8.0.3
    ports:
      - 8080:3000
    volumes:
      - grafana-data:/var/lib/grafana

  fritzbox-exporter:
    image: mxschmitt/fritzbox_exporter:latest-arm64v8
    ports:
      - 9133:9133
    command:
      - -gateway-address
      - "192.168.178.1"
      - -username
      - admin
      - -password
      - "${FRITZBOX_PASSWORD}"

  pihole-exporter:
    image: ekofr/pihole-exporter:arm64

    ports:
      - 9617:9617

    environment:
      PIHOLE_HOSTNAME: "${PIHOLE_HOSTNAME}"
      PIHOLE_PASSWORD: "${PIHOLE_PASSWORD}"
      INTERVAL: "30s"
      PORT: "9617"

volumes:
  prometheus-data:
  grafana-data:
