global:
  scrape_interval: 1m
  scrape_timeout: 10s

rule_files:
  - alert.yml

scrape_configs:
  - job_name: services
    metrics_path: /metrics
    static_configs:
      - targets:
          - "prometheus:9090"
          - "fritzbox-exporter:9133"
          - "pihole-exporter:9617"
